### ISSUE TITLE
Advent of Code Day04 code produces wrong answer

### ISSUE THREAD

**Issue by ItsMeggo** [ItsMeggo/advent_of_code_2022#1]
I looked up a tutorial to help with this code. I changed the code I had to be like the tutorial, but I still get the wrong answer...

**Comment by Jacob-Dodd** [comment]
Hey @ItsMeggo just had a quick look and your script seems to output the correct answer for me. what about the output was wrong for you?

**Comment by ItsMeggo** [comment]
@Jacob-Dodd Thank you for the sanity check! I think I just typed the answer in wrong to the advent of code website ^^'
